# This file is used by the "webots-nightly-develop" and "webots-nightly-master" appveyor projects, it is identical to the .appveyor-build-tag.yml file,
# except for the first instruction: skip_non_tags: true (which is missing here).

branches:
  # this rule applies both to branch and tag names
  except:
    - /nightly_.*/

clone_depth: 1

init:
  # The following line will display the login information for a remote desktop connection (useful to debug)
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # temporary workaround to install Python 3.9
  - bash -lc "curl -O https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe"
  - cmd /c start /wait python-3.9.0-amd64.exe /quiet TargetDir="C:\Python39-x64" Shortcuts=0 Include_launcher=1 InstallLauncherAllUsers=1 Include_debug=1
  # end of workaround
  - set PATH=C:\Python39-x64;C:\Python39-x64\Scripts;C:\msys64\usr\bin;%PATH%
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "pacman -Syu --noconfirm"
  - taskkill /f /fi "MODULES eq msys-2.0.dll"
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - echo export WEBOTS_HOME="%APPVEYOR_BUILD_FOLDER%" >> C:\msys64\home\appveyor\.bash_profile
  - type %APPVEYOR_BUILD_FOLDER%\scripts\install\bash_profile.appveyor >> C:\msys64\home\appveyor\.bash_profile
  - bash --login -c "cd $WEBOTS_HOME_PATH; git submodule init; git submodule update"
  - bash --login -c "$WEBOTS_HOME_PATH/scripts/install/msys64_installer.sh --all"
  - bash --login -c "$WEBOTS_HOME_PATH/scripts/install/nodejs_windows_installer.sh"
  - bash --login -c "$WEBOTS_HOME_PATH/scripts/install/inno_setup_installer.sh"
  - python -m pip install --upgrade pip
  - pip install PyGithub
  # The following line make the session on the virtual machine last some time to allow remote desktop session debugging
  # - ps: Start-Sleep -s 3600

build_script:
  - set PATH=C:\Python39-x64;C:\Python39-x64\Scripts;C:\msys64\usr\bin;%PATH%
  - set PYTHON39_HOME=/C/Python39-x64
  - set WEBOTS_HOME=%APPVEYOR_BUILD_FOLDER%
  - ps: if ($env:APPVEYOR_REPO_TAG -ne "true") { python $env:APPVEYOR_BUILD_FOLDER\scripts\packaging\set_commit_and_date_in_version.py $env:APPVEYOR_REPO_COMMIT }
  - bash --login -c "cd $WEBOTS_HOME_PATH; make distrib -j4"
  - python %APPVEYOR_BUILD_FOLDER%\scripts\packaging\publish_release.py --key=%GITHUB_API_KEY% --repo=%APPVEYOR_REPO_NAME% --branch=%APPVEYOR_REPO_BRANCH% --commit=%APPVEYOR_REPO_COMMIT% --tag=%APPVEYOR_REPO_TAG_NAME%
